name: Build PSP Game
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and Build Raylib
        run: |
          # Installiamo i pacchetti necessari per compilare le librerie
          if command -v apk >/dev/null; then
            apk add --no-cache git make build-base zlib-dev libpng-dev
          elif command -v apt-get >/dev/null; then
            apt-get update && apt-get install -y git make build-essential zlib1g-dev libpng-dev
          fi
          
          # Scarichiamo e compiliamo Raylib
          git clone https://github.com/raylib4Consoles/raylib.git --branch raylib4Consoles
          cd raylib/src
          make PLATFORM=PLATFORM_PSP -j$(nproc)
          
          # Installiamo Raylib nelle cartelle dell'SDK PSP
          export PSPDEV_PATH=$(psp-config --psp-prefix)
          mkdir -p $PSPDEV_PATH/include
          mkdir -p $PSPDEV_PATH/lib
          cp libraylib.a $PSPDEV_PATH/lib/
          cp *.h $PSPDEV_PATH/include/
      - name: Compile Game
        run: |
          make
      - name: Upload Bundle
        uses: actions/upload-artifact@v4
        with:
          name: LFS_PSP_BUNDLE
          path: |
            EBOOT.PBP
            car.obj
            track.obj
