name: Build PSP Game
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and Build Raylib
        run: |
          apk add --no-cache git make
          git clone https://github.com/raylib4Consoles/raylib.git --branch raylib4Consoles
          cd raylib/src
          make PLATFORM=PLATFORM_PSP -j$(nproc)
          # Installazione manuale nelle cartelle di sistema
          mkdir -p /usr/local/pspdev/psp/include
          mkdir -p /usr/local/pspdev/psp/lib
          cp libraylib.a /usr/local/pspdev/psp/lib/
          cp *.h /usr/local/pspdev/psp/include/
      - name: Compile
        run: |
          make
      - name: Upload Bundle
        uses: actions/upload-artifact@v4
        with:
          name: LFS_PSP_BUNDLE
          path: |
            EBOOT.PBP
            car.obj
            track.obj
